import = ["~/.config/alacritty/themes/everforest_dark.toml"]

[shell]
program = "zsh"
args = ["-l", "-c", "tmux new-session -A -D -s main"]

[window]
opacity = 0.9
dimensions = { columns = 120, lines = 30}
padding = { x = 0, y = 25}
decorations = "Transparent"
startup_mode = "Maximized"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 18

[cursor]
style = { shape = "Beam", blinking = "On"}

