CompileFlags:
  Add: [-std=c11, ...]
  If:
    FileMatch: '.*\.c$'

CompileFlags:
  Add: [-std=c++17, ...]
  If:
    FileMatch: '.*\.(cpp|cc|cxx)$'

InlayHints:
  Enabled: true
  DeducedTypes: true
  ParameterNames: true
